name: action_to_speak_updated
description: "AI based sign recognition"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.0
  lottie: ^3.0.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  image_picker: ^1.0.7
  image: ^4.1.7
  speech_to_text: ^6.6.2      # Stable version
  camera: ^0.11.4              # Compatible with hand_landmarker
  flutter_tts: ^3.8.5
  tflite_flutter: ^0.10.4       # Stable version
  hand_landmarker: ^2.2.0       # Compatible version
  google_mlkit_commons: ^0.9.0
      
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/model.tflite
    - assets/videos/book.mp4
    - assets/videos/friend.mp4
    - assets/videos/father.mp4
    - assets/videos/family.mp4
    - assets/videos/student.mp4
    - assets/videos/write.mp4
    - assets/videos/mother.mp4
    - assets/videos/read.mp4
    - assets/videos/home.mp4
