name: action_to_speak_updated
description: "AI based sign recognition"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  permission_handler: ^11.3.0
  lottie: ^3.0.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  image_picker: ^1.0.7
  image: ^4.1.7
  speech_to_text: ^6.6.2
  camera: ^0.10.5
  flutter_tts: ^3.8.5

  #  AI MODEL (IMPORTANT)
  tflite_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/model.tflite
    - assets/book.mp4
    - assets/friend.mp4
    - assets/father.mp4
    - assets/family.mp4
    - assets/student.mp4
    - assets/write.mp4
    - assets/mother.mp4
    - assets/read.mp4
    - assets/home.mp4
